from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Sequence

from action_segmentation.logging_utils import configure_logging
from action_segmentation.visualization.timeline_plot import (
    TimelineVisualizationError,
    load_evaluation_report,
    render_timeline_figure,
    select_timeline,
)

LOGGER = logging.getLogger(__name__)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render a workflow timeline from an evaluation metrics JSON file."
    )
    parser.add_argument(
        "--metrics",
        type=Path,
        default=Path("artifacts/metrics.json"),
        help="Evaluation JSON generated by scripts/evaluate_mock.py.",
    )
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--sample-id", help="Exact sample ID, for example test_0000.")
    selection.add_argument(
        "--sample-index",
        type=int,
        default=0,
        help="Zero-based timeline index when --sample-id is not supplied.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="PNG path; defaults to artifacts/timeline_<sample_id>.png.",
    )
    parser.add_argument(
        "--show-confidence",
        action="store_true",
        help="Add raw and smoothed maximum-confidence traces.",
    )
    parser.add_argument("--dpi", type=int, default=160, help="Output PNG resolution.")
    parser.add_argument(
        "--list-samples",
        action="store_true",
        help="Print sample IDs in the metrics file and exit.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    configure_logging()
    args = build_parser().parse_args(argv)
    try:
        report = load_evaluation_report(args.metrics)
        if args.list_samples:
            for item in report["timelines"]:
                print(item.get("sample_id", "unknown"))
            return 0

        sample = select_timeline(
            report,
            sample_id=args.sample_id,
            sample_index=args.sample_index,
        )
        output = args.output or Path("artifacts") / (
            f"timeline_{sample.get('sample_id', 'sample')}.png"
        )
        rendered = render_timeline_figure(
            sample,
            output,
            show_confidence=args.show_confidence,
            dpi=args.dpi,
        )
    except (
        FileNotFoundError,
        OSError,
        TimelineVisualizationError,
        TypeError,
        ValueError,
    ) as exc:
        LOGGER.error("Timeline visualization failed: %s", exc)
        return 1

    LOGGER.info("Timeline visualization saved to: %s", rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
